sonar.projectKey=softwareone-platform_{{ distribution }}
sonar.organization=softwareone-mpt-github

sonar.language=py

sonar.sources=mpt_extension_contrib/{{ python_name }}
sonar.tests=tests
sonar.inclusions=mpt_extension_contrib/{{ python_name }}/**
sonar.exclusions=tests/**,**/__init__.py

sonar.python.coverage.reportPaths=../coverage.xml
sonar.python.version=3.12
