sonar.projectKey=softwareone-platform_mpt-extension-python-contrib
sonar.organization=softwareone-mpt-github

sonar.language=py
sonar.python.version=3.12

sonar.sources=.
sonar.inclusions=**/mpt_extension_contrib/**
sonar.exclusions=**/tests/**,**/__init__.py,scripts/templates/**
